name: habbittracker
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.3
  firebase_core: ^0.4.5
  firebase_auth: ^0.16.1
  cloud_firestore: ^0.13.6
  intl: ^0.16.1
  charts_flutter: ^0.9.0
  toast: ^0.1.5
  flutter_speed_dial: ^1.2.5
  percent_indicator: ^2.1.5
  progress_dialog: ^1.2.4
  flutter_time_picker_spinner: ^1.0.6+1
  flutter_duration_picker: ^1.0.4
  jiffy: ^3.0.1
  hexcolor: ^1.0.4
  characters: ^1.0.0
  flutter_slidable: ^0.5.5
  table_calendar: ^2.2.3
  firebase_storage: ^3.1.6
  image_picker: ^0.6.7+4
  path_provider: ^1.6.11
  shared_preferences: ^0.5.10
  flutter_launcher_icons: ^0.7.5
  android_alarm_manager: ^0.4.5+11
  flutter_local_notifications: ^1.4.4+2
  sphere_bottom_navigation_bar: ^1.0.0
  workmanager: ^0.2.3
  csv: ^4.0.3
  open_file: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_icons:
  ios: true
  android: true
  image_path: "images/logo.png"

flutter:

  uses-material-design: true
  fonts:
    - family: MyFlutterApp
      fonts:
        - asset: fonts/MyFlutterApp.ttf
  assets:
    - images/

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
